package com.learning.refapp.business;

/**
 * Hello world!
 * This is an autogenerated class (from maven archetype-quickstart) and hence would be deleted
 */
@Deprecated
public class App 
{
    public static void main( String[] args )
    {
        System.out.println( "Hello World!" );
    }
}
